import userIcon from '../header/popUpMenu/popUpIcons/usericon.png';
import balanceIcon from '../header/popUpMenu/popUpIcons/balance.png';
import helpIcon from '../header/popUpMenu/popUpIcons/helpicon.png';
import logOutIcon from '../header/popUpMenu/popUpIcons/logouticon.png';

let languageData = {
  ru: {
    link_1: 'Как пользоваться?',
    link_2: 'Мои записи',
    link_3: 'Записаться к врачу',
    name: 'David Gharibyan',
    menuData: [
      { icon: userIcon, text: 'Мой профиль' },
      { icon: balanceIcon, text: 'Пополнить баланс' },
      { icon: helpIcon, text: 'FAQ' },
      { icon: logOutIcon, text: 'Выйти' },
    ],
    bookHeading: 'Записаться к врачу',
    bookText: 'Более 1500 врачей и более 50 разных специализаций',
    bookListItem_1: 'Прием в удобное для вас время, без визита в клинику',
    bookListItem_2: 'Врачи с опытом работы более 8 лет',
    bookListItem_3: 'Понятно объясним причину недуга и дадим подробную рекомендацию',
    bookBtn: 'Записаться',
    myBooks: 'мои записи',
    listItem_1: 'Предстоящие',
    listItem_2: 'Прошедшие',
    listItem_3: 'Отмененные',
    headingDecoration: 'Онлайн консультации',
    headingText: 'от врачей специалистов 24/7',
    informationText: 'Проконсультируйтесь',
    infoTextDecor: 'сейчас',
    separateText: 'или по',
    infoTextDecor_2: 'предварительной записи',
    informationText_2: 'со своего компьютера или c помощью нашего приложения, доступного в',
    store_1: 'App Store',
    and: 'и',
    store_2: 'Google Play',
    btn_book: 'Записаться',
    btn_how: 'Как это работает?',
    //----------------footer--------------------//
    footerInfo_1: 'Онлай- консульации специалистов врачей, то что предлагает данный сервис.',
    footerInfo_2: 'В нашем веб и мобильном приложении вы найдете врачей экспертов, которые окажут вам персонализированную помощь онлайн 24/7',
    footerListItem_1: 'Как пользоваться',
    footerListItem_2: 'FAQ (ответы на вопросы)',
    footerListItem_3: 'Для врачей',
    footerListItem_4: 'О сервисе',
    footerListItem_5: 'Контакты',
    footerListItem_6: 'Пользовательское соглашение',
    contactEmail: 'allodoc@mail.com',
    contactPlace: 'г. Москва. ул, Ленина 54, офис 51',
    contactTime: 'Пн-Вс с 09:00 до 18:00',
    contactPhone: '8 800 555 35 35',
    //----------------doctorUserPage--------------------//
    doctorUserPageDoctors: 'Врачи',
    doctorUserPageProffesion: 'Педиатр',
    doctorUserPageProfile: 'Профиль',
    doctorUserPagePrice: '900 / консультация',
    doctorUserPageTime: '30 минут',
    //----------------doctorUserPageProfileInfo--------------------//
    doctorUserPageCalendarHeading: 'Ближайшая запись',
    doctorUserPageCalendarText: 'Вторник 03 Марта',
    doctorUserPageEducationHeading: 'Образование',
    doctorUserPageEducationText_1: '1992 - Российский Государственный Университет',
    doctorUserPageEducationText_2: '1994 - Ординатура по специальности «Педиатрия»',
    doctorUserPageSpeacalizationHeading: 'Специализируется на лечении',
    doctorUserPageSpeacalizationText: 'История о том, как мы должны сидеть сложа руки, о том, как мы относимся к элите, как мы относимся к временным происшествиям, труду и великой долоре. Мы должны стремиться к минимальному вознаграждению, потому что это не требует больших затрат труда и не требует дополнительных затрат, как следствие этого.',
    doctorUserPageMoreHeading: 'Дополнительно',
    doctorUserPageMoreText: 'История о том, как мы должны сидеть сложа руки, о том, как мы относимся к элите, как мы относимся к временным происшествиям, труду и великой долоре. Мы должны стремиться к минимальному вознаграждению, потому что это не требует больших затрат труда и не требует дополнительных затрат, как следствие этого.',
  },
  en: {
    link_1: 'How to use?',
    link_2: 'My notes',
    link_3: 'Make an appointment',
    name: 'David Gharibyan',
    menuData: [
      { icon: userIcon, text: 'My profile' },
      { icon: balanceIcon, text: 'Top up balance' },
      { icon: helpIcon, text: 'FAQ' },
      { icon: logOutIcon, text: 'Log Out' },
    ],
    bookHeading: 'Make an appointment with a doctor',
    bookText: 'More than 1500 doctors and more than 50 different specialties',
    bookListItem_1: 'Appointment at a time convenient for you, without a visit to the clinic',
    bookListItem_2: 'Doctors with more than 8 years of experience',
    bookListItem_3: 'We will clearly explain the cause of the disease and give detailed recommendations.',
    bookBtn: 'To book',
    myBooks: 'My notes',
    listItem_1: 'Upcoming',
    listItem_2: 'Passed',
    listItem_3: 'Rejected',
    headingDecoration: 'Online consultations',
    headingText: 'from specialist doctors 24/7',
    informationText: 'Consult',
    infoTextDecor: 'now',
    separateText: 'or by',
    infoTextDecor_2: 'appointment',
    informationText_2: 'from your computer or using our app available in',
    store_1: 'App Store',
    and: 'and',
    store_2: 'Google Play',
    btn_book: 'Book',
    btn_how: 'How it works',
    //----------footer----------//
    footerInfo_1: 'Online consultations of medical specialists are what this service offers.',
    footerInfo_2: 'In our web and mobile application, you will find expert doctors who will provide you with personalized care online 24/7',
    footerListItem_1: 'How to use',
    footerListItem_2: 'FAQ (answers to questions)',
    footerListItem_3: 'For doctors',
    footerListItem_4: 'About the service',
    footerListItem_5: 'Contacts',
    footerListItem_6: 'User agreement',
    contactEmail: 'allodoc@mail.com',
    contactPlace: 'Moscow. 54 Lenin Street, office 51',
    contactTime: 'Mon-Sun from 09:00 to 18:00',
    contactPhone: '8 800 555 35 35',
    //----------------doctorUserPage--------------------//
    doctorUserPageDoctors: 'Doctors',
    doctorUserPageProffesion: 'Pediatrician',
    doctorUserPageProfile: 'Profile',
    doctorUserPagePrice: '900 / consultation',
    doctorUserPageTime: '30 minutes',
    //----------------doctorUserPageProfileInfo--------------------//
    doctorUserPageCalendarHeading: 'The nearest entry',
    doctorUserPageCalendarText: 'Tuesday 03 March',
    doctorUserPageEducationHeading: 'Education',
    doctorUserPageEducationText_1: '1992 - Russian State University',
    doctorUserPageEducationText_2: '1994 - Residency in Pediatrics',
    doctorUserPageSpeacalizationHeading: 'Hospitalized for treatment',
    doctorUserPageSpeacalizationText: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    doctorUserPageMoreHeading: 'Дополнительно',
    doctorUserPageMoreText: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
  },
};
export default languageData;
