import avatar from '../main/notes/notesCard/notesIcons/avatar.png';
import calendar from '../main/notes/notesCard/notesIcons/calendar.png';
import camera from '../main/notes/notesCard/notesIcons/camera.png';
import clock from '../main/notes/notesCard/notesIcons/clock.png';
import chat from '../main/notes/notesCard/notesIcons/chat.png';

let userDataEN = [
  {
    avatar: avatar,
    name: 'Olga Nikitina',
    staff: 'Pediator',
    stage: 'Experiance 15 years',
    date: '03 March 2021 ',
    calendar: calendar,
    hour: '16:00',
    clock: clock,
    connection: 'Video Call',
    camera: camera,
    condition: 'Upcoming',
    conditionCheck: '1',
    btn_1: 'View Notes',
    btn_2: 'View the resolution',
  },
  {
    avatar: avatar,
    name: 'Olga Nikitina',
    staff: 'Pediator',
    stage: 'Experiance 15 years',
    date: '03 March 2021 ',
    calendar: calendar,
    hour: '16:00',
    clock: clock,
    connection: 'Video Call',
    camera: camera,
    condition: 'Upcoming',
    conditionCheck: '1',
    btn_1: 'View Notes',
    btn_2: 'View the resolution',
  },
  {
    avatar: avatar,
    name: 'Olga Nikitina',
    staff: 'Pediator',
    stage: 'Experiance 15 years',
    date: '03 March 2021 ',
    calendar: calendar,
    hour: '16:00',
    clock: clock,
    connection: 'Video Call',
    camera: camera,
    condition: 'Rejected',
    conditionCheck: '3',
    btn_1: 'View Notes',
    btn_2: 'View the resolution',
  },
  {
    avatar: avatar,
    name: 'Olga Nikitina',
    staff: 'Pediator',
    stage: 'Experiance 15 years',
    date: '03 March 2021 ',
    calendar: calendar,
    hour: '16:00',
    clock: clock,
    connection: 'Video Call',
    camera: camera,
    condition: 'Upcoming',
    conditionCheck: '1',
    btn_1: 'View Notes',
    btn_2: 'View the resolution',
  },
  {
    avatar: avatar,
    name: 'Olga Nikitina',
    staff: 'Pediator',
    stage: 'Experiance 15 years',
    date: '03 March 2021 ',
    calendar: calendar,
    hour: '16:00',
    clock: clock,
    connection: 'Video Call',
    camera: camera,
    condition: 'Planned',
    conditionCheck: '1',
    btn_1: 'View Notes',
    btn_2: 'View the resolution',
  },
  {
    avatar: avatar,
    name: 'Olga Nikitina',
    staff: 'Pediator',
    stage: 'Experiance 15 years',
    date: '03 March 2021 ',
    calendar: calendar,
    hour: '16:00',
    clock: clock,
    connection: 'Video Call',
    camera: camera,
    condition: 'Passed',
    conditionCheck: '2',
    btn_1: 'View Notes',
    btn_2: 'View the resolution',
  },
  {
    avatar: avatar,
    name: 'Olga Nikitina',
    staff: 'Pediator',
    stage: 'Experiance 15 years',
    date: '03 March 2021 ',
    calendar: calendar,
    hour: '16:00',
    clock: clock,
    connection: 'Video Call',
    camera: camera,
    condition: 'Rejected',
    conditionCheck: '3',
    btn_1: 'View Notes',
    btn_2: 'View the resolution',
  },
  {
    avatar: avatar,
    name: 'Olga Nikitina',
    staff: 'Pediator',
    stage: 'Experiance 15 years',
    date: '03 March 2021 ',
    calendar: calendar,
    hour: '16:00',
    clock: clock,
    connection: 'Chat',
    camera: chat,
    condition: 'Upcoming',
    conditionCheck: '1',
    btn_1: 'View Notes',
    btn_2: 'View the resolution',
  },
  {
    avatar: avatar,
    name: 'Olga Nikitina',
    staff: 'Pediator',
    stage: 'Experiance 15 years',
    date: '03 March 2021 ',
    calendar: calendar,
    hour: '16:00',
    clock: clock,
    connection: 'Video Call',
    camera: camera,
    condition: 'Passed',
    conditionCheck: '2',
    btn_1: 'View Notes',
    btn_2: 'View the resolution',
  },
  {
    avatar: avatar,
    name: 'Olga Nikitina',
    staff: 'Pediator',
    stage: 'Experiance 15 years',
    date: '03 March 2021 ',
    calendar: calendar,
    hour: '16:00',
    clock: clock,
    connection: 'Chat',
    camera: chat,
    condition: 'Rejected',
    conditionCheck: '3',
    btn_1: 'View Notes',
    btn_2: 'View the resolution',
  },
  {
    avatar: avatar,
    name: 'Olga Nikitina',
    staff: 'Pediator',
    stage: 'Experiance 15 years',
    date: '03 March 2021 ',
    calendar: calendar,
    hour: '16:00',
    clock: clock,
    connection: 'Video Call',
    camera: camera,
    condition: 'Passed',
    conditionCheck: '2',
    btn_1: 'View Notes',
    btn_2: 'View the resolution',
  },
  {
    avatar: avatar,
    name: 'Olga Nikitina',
    staff: 'Pediator',
    stage: 'Experiance 15 years',
    date: '03 March 2021 ',
    calendar: calendar,
    hour: '16:00',
    clock: clock,
    connection: 'Video Call',
    camera: camera,
    condition: 'Passed',
    conditionCheck: '2',
    btn_1: 'View Notes',
    btn_2: 'View the resolution',
  },
  {
    avatar: avatar,
    name: 'Olga Nikitina',
    staff: 'Pediator',
    stage: 'Experiance 15 years',
    date: '03 March 2021 ',
    calendar: calendar,
    hour: '16:00',
    clock: clock,
    connection: 'Video Call',
    camera: chat,
    condition: 'Rejected',
    conditionCheck: '3',
    btn_1: 'View Notes',
    btn_2: 'View the resolution',
  },
  {
    avatar: avatar,
    name: 'Olga Nikitina',
    staff: 'Pediator',
    stage: 'Experiance 15 years',
    date: '03 March 2021 ',
    calendar: calendar,
    hour: '16:00',
    clock: clock,
    connection: 'Video Call',
    camera: camera,
    condition: 'Rejected',
    conditionCheck: '3',
    btn_1: 'View Notes',
    btn_2: 'View the resolution',
  },
  {
    avatar: avatar,
    name: 'Olga Nikitina',
    staff: 'Pediator',
    stage: 'Experiance 15 years',
    date: '03 March 2021 ',
    calendar: calendar,
    hour: '16:00',
    clock: clock,
    connection: 'Chat',
    camera: chat,
    condition: 'Passed',
    conditionCheck: '2',
    btn_1: 'View Notes',
    btn_2: 'View the resolution',
  },
];

export default userDataEN;
