import avatar from '../main/notes/notesCard/notesIcons/avatar.png';
import calendar from '../main/notes/notesCard/notesIcons/calendar.png';
import camera from '../main/notes/notesCard/notesIcons/camera.png';
import clock from '../main/notes/notesCard/notesIcons/clock.png';
import chat from '../main/notes/notesCard/notesIcons/chat.png';

let userDataRU = [
  {
    avatar: avatar,
    name: 'Ольга Никитина',
    staff: 'Педиатр',
    stage: 'Стаж 15 лет',
    date: '03 Марта 2021 ',
    calendar: calendar,
    hour: '16:00',
    clock: clock,
    connection: 'Видео связь',
    camera: camera,
    condition: 'Запланировано',
    conditionCheck: '1',
    btn_1: 'Посмотреть запись',
    btn_2: 'Посмотреть постановление',
  },
  {
    avatar: avatar,
    name: 'Ольга Никитина',
    staff: 'Педиатр',
    stage: 'Стаж 15 лет',
    date: '03 Марта 2021 ',
    calendar: calendar,
    hour: '16:00',
    clock: clock,
    connection: 'Видео связь',
    camera: camera,
    condition: 'Запланировано',
    conditionCheck: '1',
    btn_1: 'Посмотреть запись',
    btn_2: 'Посмотреть постановление',
  },
  {
    avatar: avatar,
    name: 'Ольга Никитина',
    staff: 'Педиатр',
    stage: 'Стаж 15 лет',
    date: '03 Марта 2021 ',
    calendar: calendar,
    hour: '16:00',
    clock: clock,
    connection: 'Видео связь',
    camera: camera,
    condition: 'oтмeнeнo',
    conditionCheck: '3',
    btn_1: 'Посмотреть запись',
    btn_2: 'Посмотреть постановление',
  },
  {
    avatar: avatar,
    name: 'Ольга Никитина',
    staff: 'Педиатр',
    stage: 'Стаж 15 лет',
    date: '03 Марта 2021 ',
    calendar: calendar,
    hour: '16:00',
    clock: clock,
    connection: 'Видео связь',
    camera: camera,
    condition: 'Запланировано',
    conditionCheck: '1',
    btn_1: 'Посмотреть запись',
    btn_2: 'Посмотреть постановление',
  },
  {
    avatar: avatar,
    name: 'Ольга Никитина',
    staff: 'Педиатр',
    stage: 'Стаж 15 лет',
    date: '03 Марта 2021 ',
    calendar: calendar,
    hour: '16:00',
    clock: clock,
    connection: 'Видео связь',
    camera: camera,
    condition: 'Запланировано',
    conditionCheck: '1',
    btn_1: 'Посмотреть запись',
    btn_2: 'Посмотреть постановление',
  },
  {
    avatar: avatar,
    name: 'Ольга Никитина',
    staff: 'Педиатр',
    stage: 'Стаж 15 лет',
    date: '03 Марта 2021 ',
    calendar: calendar,
    hour: '16:00',
    clock: clock,
    connection: 'Видео связь',
    camera: camera,
    condition: 'Состоялась',
    conditionCheck: '2',
    btn_1: 'Посмотреть запись',
    btn_2: 'Посмотреть постановление',
  },
  {
    avatar: avatar,
    name: 'Ольга Никитина',
    staff: 'Педиатр',
    stage: 'Стаж 15 лет',
    date: '03 Марта 2021 ',
    calendar: calendar,
    hour: '16:00',
    clock: clock,
    connection: 'Видео связь',
    camera: camera,
    condition: 'oтмeнeнo',
    conditionCheck: '3',
    btn_1: 'Посмотреть запись',
    btn_2: 'Посмотреть постановление',
  },
  {
    avatar: avatar,
    name: 'Ольга Никитина',
    staff: 'Педиатр',
    stage: 'Стаж 15 лет',
    date: '03 Марта 2021 ',
    calendar: calendar,
    hour: '16:00',
    clock: clock,
    connection: 'Чат',
    camera: chat,
    condition: 'Запланировано',
    conditionCheck: '1',
    btn_1: 'Посмотреть запись',
    btn_2: 'Посмотреть постановление',
  },
  {
    avatar: avatar,
    name: 'Ольга Никитина',
    staff: 'Педиатр',
    stage: 'Стаж 15 лет',
    date: '03 Марта 2021 ',
    calendar: calendar,
    hour: '16:00',
    clock: clock,
    connection: 'Видео связь',
    camera: camera,
    condition: 'Состоялась',
    conditionCheck: '2',
    btn_1: 'Посмотреть запись',
    btn_2: 'Посмотреть постановление',
  },
  {
    avatar: avatar,
    name: 'Ангелина Марковна',
    staff: 'Оториноларинголог (ЛОР), Терапевт',
    stage: 'Стаж 5 лет',
    date: '16 Марта 2021 ',
    calendar: calendar,
    hour: '23:00',
    clock: clock,
    connection: 'Чат',
    camera: chat,
    condition: 'oтмeнeнo',
    conditionCheck: '3',
    btn_1: 'Посмотреть запись',
    btn_2: 'Посмотреть постановление',
  },
  {
    avatar: avatar,
    name: 'Юлия Тихоновна',
    staff: 'Оториноларинголог (ЛОР), Терапевт',
    stage: 'Стаж 7 лет',
    date: '23 август 2022 ',
    calendar: calendar,
    hour: '23:00',
    clock: clock,
    connection: 'Видео связь',
    camera: camera,
    condition: 'Состоялась',
    conditionCheck: '2',
    btn_1: 'Посмотреть запись',
    btn_2: 'Посмотреть постановление',
  },
  {
    avatar: avatar,
    name: 'Юлия Тихоновна',
    staff: 'Оториноларинголог (ЛОР), Терапевт',
    stage: 'Стаж 7 лет',
    date: '23 август 2022 ',
    calendar: calendar,
    hour: '23:00',
    clock: clock,
    connection: 'Видео связь',
    camera: camera,
    condition: 'Состоялась',
    conditionCheck: '2',
    btn_1: 'Посмотреть запись',
    btn_2: 'Посмотреть постановление',
  },
  {
    avatar: avatar,
    name: 'Юлия Тихоновна',
    staff: 'Оториноларинголог (ЛОР), Терапевт',
    stage: 'Стаж 7 лет',
    date: '23 август 2022 ',
    calendar: calendar,
    hour: '23:00',
    clock: clock,
    connection: 'Чат',
    camera: chat,
    condition: 'oтмeнeнo',
    conditionCheck: '3',
    btn_1: 'Посмотреть запись',
    btn_2: 'Посмотреть постановление',
  },
  {
    avatar: avatar,
    name: 'Юлия Тихоновна',
    staff: 'Оториноларинголог (ЛОР), Терапевт',
    stage: 'Стаж 7 лет',
    date: '23 август 2022 ',
    calendar: calendar,
    hour: '23:00',
    clock: clock,
    connection: 'Видео связь',
    camera: camera,
    condition: 'oтмeнeнo',
    conditionCheck: '3',
    btn_1: 'Посмотреть запись',
    btn_2: 'Посмотреть постановление',
  },
  {
    avatar: avatar,
    name: 'Юлия Тихоновна',
    staff: 'Оториноларинголог (ЛОР), Терапевт',
    stage: 'Стаж 7 лет',
    date: '23 август 2022 ',
    calendar: calendar,
    hour: '23:00',
    clock: clock,
    connection: 'Чат',
    camera: chat,
    condition: 'Состоялась',
    conditionCheck: '2',
    btn_1: 'Посмотреть запись',
    btn_2: 'Посмотреть постановление',
  },
];

export default userDataRU;
