import avatar from '../components/main/notes/notesCard/notesIcon/avatar.png';
import calendar from '../components/main/notes/notesCard/notesIcon/calendar.png';
import camera from '../components/main/notes/notesCard/notesIcon/camera.png';
import clock from '../components/main/notes/notesCard/notesIcon/clock.png';
import chat from '../components/main/notes/notesCard/notesIcon/chat.png';

let userData = {
  ru: [
    {
      avatar: avatar,
      doctorName: 'Ольга Никитина',
      staff: 'Педиатр',
      stage: 'Стаж 15 лет',
      date: '03 Марта 2021 ',
      calendar: calendar,
      hour: '16:00',
      clock: clock,
      connection: 'Видео связь',
      camera: camera,
      condition: 'Запланировано',
      conditionCheck: '1',
      btn_1: 'Посмотреть запись',
      btn_2: 'Посмотреть постановление',
    },
    {
      avatar: avatar,
      doctorName: 'Ольга Никитина',
      staff: 'Педиатр',
      stage: 'Стаж 15 лет',
      date: '03 Марта 2021 ',
      calendar: calendar,
      hour: '16:00',
      clock: clock,
      connection: 'Видео связь',
      camera: camera,
      condition: 'Запланировано',
      conditionCheck: '1',
      btn_1: 'Посмотреть запись',
      btn_2: 'Посмотреть постановление',
    },
    {
      avatar: avatar,
      doctorName: 'Ольга Никитина',
      staff: 'Педиатр',
      stage: 'Стаж 15 лет',
      date: '03 Марта 2021 ',
      calendar: calendar,
      hour: '16:00',
      clock: clock,
      connection: 'Видео связь',
      camera: camera,
      condition: 'oтмeнeнo',
      conditionCheck: '3',
      btn_1: 'Посмотреть запись',
      btn_2: 'Посмотреть постановление',
    },
    {
      avatar: avatar,
      doctorName: 'Ольга Никитина',
      staff: 'Педиатр',
      stage: 'Стаж 15 лет',
      date: '03 Марта 2021 ',
      calendar: calendar,
      hour: '16:00',
      clock: clock,
      connection: 'Видео связь',
      camera: camera,
      condition: 'Запланировано',
      conditionCheck: '1',
      btn_1: 'Посмотреть запись',
      btn_2: 'Посмотреть постановление',
    },
    {
      avatar: avatar,
      doctorName: 'Ольга Никитина',
      staff: 'Педиатр',
      stage: 'Стаж 15 лет',
      date: '03 Марта 2021 ',
      calendar: calendar,
      hour: '16:00',
      clock: clock,
      connection: 'Видео связь',
      camera: camera,
      condition: 'Запланировано',
      conditionCheck: '1',
      btn_1: 'Посмотреть запись',
      btn_2: 'Посмотреть постановление',
    },
    {
      avatar: avatar,
      doctorName: 'Ольга Никитина',
      staff: 'Педиатр',
      stage: 'Стаж 15 лет',
      date: '03 Марта 2021 ',
      calendar: calendar,
      hour: '16:00',
      clock: clock,
      connection: 'Видео связь',
      camera: camera,
      condition: 'Состоялась',
      conditionCheck: '2',
      btn_1: 'Посмотреть запись',
      btn_2: 'Посмотреть постановление',
    },
    {
      avatar: avatar,
      doctorName: 'Ольга Никитина',
      staff: 'Педиатр',
      stage: 'Стаж 15 лет',
      date: '03 Марта 2021 ',
      calendar: calendar,
      hour: '16:00',
      clock: clock,
      connection: 'Видео связь',
      camera: camera,
      condition: 'oтмeнeнo',
      conditionCheck: '3',
      btn_1: 'Посмотреть запись',
      btn_2: 'Посмотреть постановление',
    },
    {
      avatar: avatar,
      doctorName: 'Ольга Никитина',
      staff: 'Педиатр',
      stage: 'Стаж 15 лет',
      date: '03 Марта 2021 ',
      calendar: calendar,
      hour: '16:00',
      clock: clock,
      connection: 'Чат',
      camera: chat,
      condition: 'Запланировано',
      conditionCheck: '1',
      btn_1: 'Посмотреть запись',
      btn_2: 'Посмотреть постановление',
    },
    {
      avatar: avatar,
      doctorName: 'Ольга Никитина',
      staff: 'Педиатр',
      stage: 'Стаж 15 лет',
      date: '03 Марта 2021 ',
      calendar: calendar,
      hour: '16:00',
      clock: clock,
      connection: 'Видео связь',
      camera: camera,
      condition: 'Состоялась',
      conditionCheck: '2',
      btn_1: 'Посмотреть запись',
      btn_2: 'Посмотреть постановление',
    },
    {
      avatar: avatar,
      doctorName: 'Ангелина Марковна',
      staff: 'Оториноларинголог (ЛОР), Терапевт',
      stage: 'Стаж 5 лет',
      date: '16 Марта 2021 ',
      calendar: calendar,
      hour: '23:00',
      clock: clock,
      connection: 'Чат',
      camera: chat,
      condition: 'oтмeнeнo',
      conditionCheck: '3',
      btn_1: 'Посмотреть запись',
      btn_2: 'Посмотреть постановление',
    },
    {
      avatar: avatar,
      doctorName: 'Юлия Тихоновна',
      staff: 'Оториноларинголог (ЛОР), Терапевт',
      stage: 'Стаж 7 лет',
      date: '23 август 2022 ',
      calendar: calendar,
      hour: '23:00',
      clock: clock,
      connection: 'Видео связь',
      camera: camera,
      condition: 'Состоялась',
      conditionCheck: '2',
      btn_1: 'Посмотреть запись',
      btn_2: 'Посмотреть постановление',
    },
    {
      avatar: avatar,
      doctorName: 'Юлия Тихоновна',
      staff: 'Оториноларинголог (ЛОР), Терапевт',
      stage: 'Стаж 7 лет',
      date: '23 август 2022 ',
      calendar: calendar,
      hour: '23:00',
      clock: clock,
      connection: 'Видео связь',
      camera: camera,
      condition: 'Состоялась',
      conditionCheck: '2',
      btn_1: 'Посмотреть запись',
      btn_2: 'Посмотреть постановление',
    },
    {
      avatar: avatar,
      doctorName: 'Юлия Тихоновна',
      staff: 'Оториноларинголог (ЛОР), Терапевт',
      stage: 'Стаж 7 лет',
      date: '23 август 2022 ',
      calendar: calendar,
      hour: '23:00',
      clock: clock,
      connection: 'Чат',
      camera: chat,
      condition: 'oтмeнeнo',
      conditionCheck: '3',
      btn_1: 'Посмотреть запись',
      btn_2: 'Посмотреть постановление',
    },
    {
      avatar: avatar,
      doctorName: 'Юлия Тихоновна',
      staff: 'Оториноларинголог (ЛОР), Терапевт',
      stage: 'Стаж 7 лет',
      date: '23 август 2022 ',
      calendar: calendar,
      hour: '23:00',
      clock: clock,
      connection: 'Видео связь',
      camera: camera,
      condition: 'oтмeнeнo',
      conditionCheck: '3',
      btn_1: 'Посмотреть запись',
      btn_2: 'Посмотреть постановление',
    },
    {
      avatar: avatar,
      doctorName: 'Юлия Тихоновна',
      staff: 'Оториноларинголог (ЛОР), Терапевт',
      stage: 'Стаж 7 лет',
      date: '23 август 2022 ',
      calendar: calendar,
      hour: '23:00',
      clock: clock,
      connection: 'Чат',
      camera: chat,
      condition: 'Состоялась',
      conditionCheck: '2',
      btn_1: 'Посмотреть запись',
      btn_2: 'Посмотреть постановление',
    },
  ],
  en: [
    {
      avatar: avatar,
      doctorName: 'Olga Nikitina',
      staff: 'Pediator',
      stage: 'Experiance 15 years',
      date: '03 March 2021 ',
      calendar: calendar,
      hour: '16:00',
      clock: clock,
      connection: 'Video Call',
      camera: camera,
      condition: 'Upcoming',
      conditionCheck: '1',
      btn_1: 'View Notes',
      btn_2: 'View the resolution',
    },
    {
      avatar: avatar,
      doctorName: 'Olga Nikitina',
      staff: 'Pediator',
      stage: 'Experiance 15 years',
      date: '03 March 2021 ',
      calendar: calendar,
      hour: '16:00',
      clock: clock,
      connection: 'Video Call',
      camera: camera,
      condition: 'Upcoming',
      conditionCheck: '1',
      btn_1: 'View Notes',
      btn_2: 'View the resolution',
    },
    {
      avatar: avatar,
      doctorName: 'Olga Nikitina',
      staff: 'Pediator',
      stage: 'Experiance 15 years',
      date: '03 March 2021 ',
      calendar: calendar,
      hour: '16:00',
      clock: clock,
      connection: 'Video Call',
      camera: camera,
      condition: 'Rejected',
      conditionCheck: '3',
      btn_1: 'View Notes',
      btn_2: 'View the resolution',
    },
    {
      avatar: avatar,
      doctorName: 'Olga Nikitina',
      staff: 'Pediator',
      stage: 'Experiance 15 years',
      date: '03 March 2021 ',
      calendar: calendar,
      hour: '16:00',
      clock: clock,
      connection: 'Video Call',
      camera: camera,
      condition: 'Upcoming',
      conditionCheck: '1',
      btn_1: 'View Notes',
      btn_2: 'View the resolution',
    },
    {
      avatar: avatar,
      doctorName: 'Olga Nikitina',
      staff: 'Pediator',
      stage: 'Experiance 15 years',
      date: '03 March 2021 ',
      calendar: calendar,
      hour: '16:00',
      clock: clock,
      connection: 'Video Call',
      camera: camera,
      condition: 'Planned',
      conditionCheck: '1',
      btn_1: 'View Notes',
      btn_2: 'View the resolution',
    },
    {
      avatar: avatar,
      doctorName: 'Olga Nikitina',
      staff: 'Pediator',
      stage: 'Experiance 15 years',
      date: '03 March 2021 ',
      calendar: calendar,
      hour: '16:00',
      clock: clock,
      connection: 'Video Call',
      camera: camera,
      condition: 'Passed',
      conditionCheck: '2',
      btn_1: 'View Notes',
      btn_2: 'View the resolution',
    },
    {
      avatar: avatar,
      doctorName: 'Olga Nikitina',
      staff: 'Pediator',
      stage: 'Experiance 15 years',
      date: '03 March 2021 ',
      calendar: calendar,
      hour: '16:00',
      clock: clock,
      connection: 'Video Call',
      camera: camera,
      condition: 'Rejected',
      conditionCheck: '3',
      btn_1: 'View Notes',
      btn_2: 'View the resolution',
    },
    {
      avatar: avatar,
      doctorName: 'Olga Nikitina',
      staff: 'Pediator',
      stage: 'Experiance 15 years',
      date: '03 March 2021 ',
      calendar: calendar,
      hour: '16:00',
      clock: clock,
      connection: 'Chat',
      camera: chat,
      condition: 'Upcoming',
      conditionCheck: '1',
      btn_1: 'View Notes',
      btn_2: 'View the resolution',
    },
    {
      avatar: avatar,
      doctorName: 'Olga Nikitina',
      staff: 'Pediator',
      stage: 'Experiance 15 years',
      date: '03 March 2021 ',
      calendar: calendar,
      hour: '16:00',
      clock: clock,
      connection: 'Video Call',
      camera: camera,
      condition: 'Passed',
      conditionCheck: '2',
      btn_1: 'View Notes',
      btn_2: 'View the resolution',
    },
    {
      avatar: avatar,
      doctorName: 'Olga Nikitina',
      staff: 'Pediator',
      stage: 'Experiance 15 years',
      date: '03 March 2021 ',
      calendar: calendar,
      hour: '16:00',
      clock: clock,
      connection: 'Chat',
      camera: chat,
      condition: 'Rejected',
      conditionCheck: '3',
      btn_1: 'View Notes',
      btn_2: 'View the resolution',
    },
    {
      avatar: avatar,
      doctorName: 'Olga Nikitina',
      staff: 'Pediator',
      stage: 'Experiance 15 years',
      date: '03 March 2021 ',
      calendar: calendar,
      hour: '16:00',
      clock: clock,
      connection: 'Video Call',
      camera: camera,
      condition: 'Passed',
      conditionCheck: '2',
      btn_1: 'View Notes',
      btn_2: 'View the resolution',
    },
    {
      avatar: avatar,
      doctorName: 'Olga Nikitina',
      staff: 'Pediator',
      stage: 'Experiance 15 years',
      date: '03 March 2021 ',
      calendar: calendar,
      hour: '16:00',
      clock: clock,
      connection: 'Video Call',
      camera: camera,
      condition: 'Passed',
      conditionCheck: '2',
      btn_1: 'View Notes',
      btn_2: 'View the resolution',
    },
    {
      avatar: avatar,
      doctorName: 'Olga Nikitina',
      staff: 'Pediator',
      stage: 'Experiance 15 years',
      date: '03 March 2021 ',
      calendar: calendar,
      hour: '16:00',
      clock: clock,
      connection: 'Video Call',
      camera: chat,
      condition: 'Rejected',
      conditionCheck: '3',
      btn_1: 'View Notes',
      btn_2: 'View the resolution',
    },
    {
      avatar: avatar,
      doctorName: 'Olga Nikitina',
      staff: 'Pediator',
      stage: 'Experiance 15 years',
      date: '03 March 2021 ',
      calendar: calendar,
      hour: '16:00',
      clock: clock,
      connection: 'Video Call',
      camera: camera,
      condition: 'Rejected',
      conditionCheck: '3',
      btn_1: 'View Notes',
      btn_2: 'View the resolution',
    },
    {
      avatar: avatar,
      doctorName: 'Olga Nikitina',
      staff: 'Pediator',
      stage: 'Experiance 15 years',
      date: '03 March 2021 ',
      calendar: calendar,
      hour: '16:00',
      clock: clock,
      connection: 'Chat',
      camera: chat,
      condition: 'Passed',
      conditionCheck: '2',
      btn_1: 'View Notes',
      btn_2: 'View the resolution',
    },
  ],
};

export default userData;
